# Generated by Django 3.0.1 on 2020-01-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0002_auto_20200101_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='progress',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
