# Generated by Django 3.0.1 on 2020-01-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0003_skills_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='address',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='summary',
            name='summary',
            field=models.CharField(max_length=2083),
        ),
    ]
