# Generated by Django 3.0.1 on 2020-01-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0004_auto_20200105_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='emailid',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
