# Generated by Django 3.0.1 on 2020-01-06 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0006_auto_20200105_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='email_id',
            new_name='social',
        ),
    ]
