# Generated by Django 3.0.1 on 2020-01-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0007_auto_20200105_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='id',
            field=models.CharField(auto_created=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
