# Generated by Django 3.0.1 on 2020-01-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0008_auto_20200106_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='year',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
