# Generated by Django 3.0.1 on 2020-01-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0010_auto_20200108_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='progress',
        ),
        migrations.AddField(
            model_name='skills',
            name='url',
            field=models.CharField(blank=True, max_length=2083),
        ),
    ]
