# Generated by Django 3.0.1 on 2020-01-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0011_auto_20200111_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=2083)),
            ],
        ),
    ]
